[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "move erase wish mention soccer alter dial bargain undo weapon cinnamon maple ivory dance clever deposit flee shrimp present middle grace ball gold timber"